services:
  api_analysis:
    build: ./Analisis
    ports:
      - "3001:3001"
    networks:
      - config_services_app_network

  api_muestras:
    build: ./Muestras
    ports:
      - "3002:3002"
    networks:
      - config_services_app_network
    environment:
      - MONGO_URI_LOCAL=mongodb://admin:admin@db_proyect:27017/laboratorio?authSource=admin
      - PORT_EXPRESS=3002

  db_proyect:
    image: mongo:6
    container_name: db_proyect
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: laboratorio
    ports:
      - "27017:27017"
    networks:
      - config_services_app_network
    volumes:
      - mongo_data:/data/db

  esbservice:
    build: ./Esb-Services
    ports:
      - "3500:8080"
    networks:
      - config_services_app_network

networks:
  config_services_app_network:
    external: true

volumes:
  mongo_data:
  image_products: