services:
  rabbitmq_eco:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq_eco
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app_network
  db_proyect:
    image: mongo:8.0.10-rc0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - app_network
    volumes:
      - dataNoSQL:/data/db
  token_cache:
    image: redis:7.4.4-alpine3.21
    container_name: token_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dataNoSQL: